# Generated by Django 2.2.5 on 2021-02-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderitem_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
