# Generated by Django 2.2.5 on 2021-02-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210211_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='use_default_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
