# Generated by Django 2.2.5 on 2021-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210214_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentviapaytm',
            name='checksum',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentviapaytm',
            name='order_id',
            field=models.CharField(max_length=250),
        ),
    ]
