# Generated by Django 2.2.5 on 2021-03-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210216_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORD', 'Order Received'), ('OFD', 'Out For Delivery'), ('OD', 'Order Delivered')], default='ORD', max_length=4),
        ),
    ]
