# Generated by Django 2.2.5 on 2021-03-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210304_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORD', 'Order Received'), ('OFD', 'Out For Delivery'), ('D', 'Dispatch'), ('OD', 'Order Delivered')], default='ORD', max_length=4),
        ),
    ]
